# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0101c4d5776aaf79c4a2a8f93022d5639924dc16434f3090afa928b64ed8d007f248c2305d70501d67977a437f96d843d33a110f6a4e4f53920c50d3d0f47017

test:
  secret_key_base: a8b527e96ad8c41982f042754852d28ee9809b558e926f21d3dfa94c95d98a06f4f8768ba99faad9d540ec069567b1f549120251981e4290ab4ec52e30f0d4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
